name: Build VM with Gradle

on: [push, pull-request]

jobs:
  build-vm-gradle:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
